### PR TITLE
added immersed boundary bathymetry, and switched to T/S 

### PR DESCRIPTION
**Pull request by zhazorken**
@tomchor 

I'm having an error when running this on GPUs (it works on CPU) that pops up when I 
try to set up the immersed boundary bathymetry. It says it's out of resources? Can you maybe test on a GPU to see if you're getting the same error? 

```Julia

┌ Warning: CUDA runtime library libcusparse.so.12 was loaded from a system path. This may cause errors.
│ Ensure that you have not set the LD_LIBRARY_PATH environment variable, or that it does not contain paths to CUDA libraries.
└ @ CUDA /glade/work/kenzhao/.julia/packages/CUDA/rXson/src/initialization.jl:189
ERROR: LoadError: CUDA error: too many resources requested for launch (code 701, ERROR_LAUNCH_OUT_OF_RESOURCES)
Stacktrace:
  [1] throw_api_error(res::CUDA.cudaError_enum)
    @ CUDA /glade/work/kenzhao/.julia/packages/CUDA/rXson/lib/cudadrv/libcuda.jl:27
  [2] check
    @ /glade/work/kenzhao/.julia/packages/CUDA/rXson/lib/cudadrv/libcuda.jl:34 [inlined]
  [3] cuLaunchKernel
    @ /glade/work/kenzhao/.julia/packages/CUDA/rXson/lib/utils/call.jl:26 [inlined]
  [4] (::CUDA.var"#891#892"{Bool, Int64, CUDA.CuStream, CUDA.CuFunction, CUDA.CuDim3, CUDA.CuDim3})(kernelParams::Vector{Ptr{Nothing}})
    @ CUDA /glade/work/kenzhao/.julia/packages/CUDA/rXson/lib/cudadrv/execution.jl:69
  [5] macro expansion
    @ /glade/work/kenzhao/.julia/packages/CUDA/rXson/lib/cudadrv/execution.jl:33 [inlined]
  [6] macro expansion
    @ ./none:0 [inlined]
  [7] pack_arguments(::CUDA.var"#891#892"{Bool, Int64, CUDA.CuStream, CUDA.CuFunction, CUDA.CuDim3, CUDA.CuDim3}, ::CUDA.KernelState, ::CartesianIndices{3, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}}, ::CartesianIndices{3, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}}, ::CUDA.CuDeviceArray{Float64, 4, 1}, ::Field{Center, Center, Nothing, Nothing, Nothing, Nothing, OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}, Float64, Nothing, Nothing, Nothing})
    @ CUDA ./none:0
  [8] #launch#890
    @ /glade/work/kenzhao/.julia/packages/CUDA/rXson/lib/cudadrv/execution.jl:62 [inlined]
  [9] #896
    @ /glade/work/kenzhao/.julia/packages/CUDA/rXson/lib/cudadrv/execution.jl:136 [inlined]
 [10] macro expansion
    @ /glade/work/kenzhao/.julia/packages/CUDA/rXson/lib/cudadrv/execution.jl:95 [inlined]
 [11] macro expansion
    @ ./none:0 [inlined]
 [12] convert_arguments
    @ ./none:0 [inlined]
 [13] #cudacall#895
    @ /glade/work/kenzhao/.julia/packages/CUDA/rXson/lib/cudadrv/execution.jl:135 [inlined]
 [14] cudacall
    @ /glade/work/kenzhao/.julia/packages/CUDA/rXson/lib/cudadrv/execution.jl:134 [inlined]
 [15] macro expansion
    @ /glade/work/kenzhao/.julia/packages/CUDA/rXson/src/compiler/execution.jl:258 [inlined]
 [16] macro expansion
    @ ./none:0 [inlined]
 [17] call(::CUDA.HostKernel{typeof(CUDA.partial_mapreduce_grid), Tuple{typeof(identity), typeof(max), Nothing, CartesianIndices{3, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}}, CartesianIndices{3, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}}, Val{true}, CUDA.CuDeviceArray{Float64, 4, 1}, Field{Center, Center, Nothing, Nothing, Nothing, Nothing, OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}, Float64, Nothing, Nothing, Nothing}}}, ::typeof(identity), ::typeof(max), ::Nothing, ::CartesianIndices{3, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}}, ::CartesianIndices{3, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}}, ::Val{true}, ::CUDA.CuDeviceArray{Float64, 4, 1}, ::Field{Center, Center, Nothing, Nothing, Nothing, Nothing, OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}, Float64, Nothing, Nothing, Nothing}; call_kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:threads, :blocks, :shmem), Tuple{Int64, Int64, Int64}}})
    @ CUDA ./none:0
 [18] (::CUDA.HostKernel{typeof(CUDA.partial_mapreduce_grid), Tuple{typeof(identity), typeof(max), Nothing, CartesianIndices{3, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}}, CartesianIndices{3, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}}, Val{true}, CUDA.CuDeviceArray{Float64, 4, 1}, Field{Center, Center, Nothing, Nothing, Nothing, Nothing, OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}, Float64, Nothing, Nothing, Nothing}}})(::Function, ::Vararg{Any}; threads::Int64, blocks::Int64, kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:shmem,), Tuple{Int64}}})
    @ CUDA /glade/work/kenzhao/.julia/packages/CUDA/rXson/src/compiler/execution.jl:381
 [19] HostKernel
    @ /glade/work/kenzhao/.julia/packages/CUDA/rXson/src/compiler/execution.jl:380 [inlined]
 [20] macro expansion
    @ /glade/work/kenzhao/.julia/packages/CUDA/rXson/src/compiler/execution.jl:106 [inlined]


```

### CODE REVIEW

**Comment by tomchor** [comment]
OKay, two questions:

1. Where the PBS file to submit it? I only see three files in whole repo.
2. What happened to #1? Did you fix those errors? One error at a time.

**Comment by zhazorken** [comment]
1. Oops I just uploaded the pbs file.
2. I spend a long time trying to figure out the other error and couldn't. I sidestepped it by changing to T/S instead of just buoyancy, which will be better a configuration anyway and worked easily. (Still interested by what went wrong with the buoyancy nudging, but it doesn't limit the progress).

**Comment by tomchor** [comment]
> 1. Oops I just uploaded the pbs file.
> 2. I spend a long time trying to figure out the other error and couldn't. I sidestepped it by changing to T/S instead of just buoyancy, which will be better a configuration anyway and worked easily. (Still interested by what went wrong with the buoyancy nudging, but it doesn't limit the progress).

Okay so this same code that's here in the PR runs on the CPU?

**Comment by tomchor** [comment]
Also you should probably change the name of the main file from `iceplume.jl` to avoid confusion.

**Comment by zhazorken** [comment]
Yes it runs on a CPU.

**Comment by tomchor** [comment]
> Yes it runs on a CPU.

Nope. I'm trying to run this branch rn and it's giving me lots of errors, none of which is the one you mentioned at the top. One after the other. First there was a leftover `end` somewhere, then a couple of functions weren't defined...

Can you please make sure that this branch actually runs? My guess is that you didn't actually push all the changes you think you pushed and there's leftover code here. I'll see if I have time tomorrow or over the weekend to see this after you fix the code.

**Comment by zhazorken** [comment]
Yeah I somehow uploaded the wrong directory, I'll start a new pull request (because I renamed some of the files).

**Pull request closed without merging**
